name: archive_async
version: 0.0.1
description: >-
  Used to asynchronously decompress files and load data on demand, zip is currently supported.
repository: https://github.com/xioxin/async-archive
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.3.0
  crypto: ^3.0.0
  path: ^1.8.0

dev_dependencies:
  http: ^0.13.3
  lints: ^1.0.0
  test: ^1.17.0
  dio: ^4.0.0
  filesize: ^2.0.0
